ALTER TABLE "auth_user" ADD COLUMN "public_sequence" integer;--> statement-breakpoint
WITH numbered_members AS (
  SELECT
    "id",
    row_number() OVER (ORDER BY "created_at", "id")::integer AS "public_sequence"
  FROM "auth_user"
)
UPDATE "auth_user"
SET "public_sequence" = numbered_members."public_sequence"
FROM numbered_members
WHERE "auth_user"."id" = numbered_members."id";--> statement-breakpoint
ALTER TABLE "auth_user" ALTER COLUMN "public_sequence" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "auth_user" ALTER COLUMN "public_sequence" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "auth_user_public_sequence" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval(
  pg_get_serial_sequence('auth_user', 'public_sequence'),
  COALESCE(MAX("public_sequence"), 1),
  COUNT(*) > 0
) FROM "auth_user";--> statement-breakpoint
ALTER TABLE "auth_user" ADD CONSTRAINT "auth_user_public_sequence_unique" UNIQUE("public_sequence");