import { sql } from 'drizzle-orm';
import { bigint, check, index, pgTable, text, timestamp, unique, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { user } from './auth.schema';
import { ledgerTransactions } from './ledger.schema';
import { moneyPolicyRevisions } from './payments.schema';

const time = (name: string) => timestamp(name, { withTimezone: true });
const id = () => uuid('id').defaultRandom().primaryKey();
const actor = { actorUserId: text('actor_user_id').references(() => user.id), source: text('source').notNull(), reason: text('reason'), occurredAt: time('occurred_at').defaultNow().notNull() };

export const jobs = pgTable('jobs', {
  id: id(), employerUserId: text('employer_user_id').notNull().references(() => user.id), selectedWorkerUserId: text('selected_worker_user_id').references(() => user.id),
  title: text('title').notNull(), description: text('description').notNull(), amountBaht: bigint('amount_baht', { mode: 'bigint' }).notNull(), platformFeeBps: bigint('platform_fee_bps', { mode: 'number' }).notNull(), platformFeeBaht: bigint('platform_fee_baht', { mode: 'bigint' }).notNull(), workerNetBaht: bigint('worker_net_baht', { mode: 'bigint' }).notNull(),
  policyRevisionId: uuid('policy_revision_id').notNull().references(() => moneyPolicyRevisions.id), status: text('status').notNull(),
  applicationDeadlineAt: time('application_deadline_at').notNull(), workDeadlineAt: time('work_deadline_at').notNull(), assignedAt: time('assigned_at'), completedAt: time('completed_at'), createdAt: time('created_at').defaultNow().notNull(), updatedAt: time('updated_at').defaultNow().notNull(),
}, (t) => [check('jobs_positive_amount_chk', sql`${t.amountBaht} > 0 and ${t.platformFeeBps} between 0 and 10000 and ${t.platformFeeBaht} >= 0 and ${t.workerNetBaht} >= 0 and ${t.platformFeeBaht} + ${t.workerNetBaht} = ${t.amountBaht}`), check('jobs_deadlines_chk', sql`${t.applicationDeadlineAt} < ${t.workDeadlineAt}`), check('jobs_distinct_parties_chk', sql`${t.selectedWorkerUserId} is null or ${t.selectedWorkerUserId} <> ${t.employerUserId}`), uniqueIndex('jobs_one_engagement_per_worker_uidx').on(t.selectedWorkerUserId).where(sql`${t.status} in ('ASSIGNED','OVERDUE','IN_REVIEW','DISPUTED')`), index('jobs_application_scheduler_idx').on(t.status, t.applicationDeadlineAt), index('jobs_work_scheduler_idx').on(t.status, t.workDeadlineAt)]);

export const jobStatusHistory = pgTable('job_status_history', { id: id(), jobId: uuid('job_id').notNull().references(() => jobs.id), fromStatus: text('from_status'), toStatus: text('to_status').notNull(), ...actor }, (t) => [index('job_status_history_job_idx').on(t.jobId, t.occurredAt)]);

export const jobApplications = pgTable('job_applications', { id: id(), jobId: uuid('job_id').notNull().references(() => jobs.id), workerUserId: text('worker_user_id').notNull().references(() => user.id), message: text('message').notNull(), status: text('status').notNull(), createdAt: time('created_at').defaultNow().notNull(), updatedAt: time('updated_at').defaultNow().notNull() }, (t) => [unique('job_applications_job_worker_uq').on(t.jobId, t.workerUserId), index('job_applications_worker_status_idx').on(t.workerUserId, t.status)]);
export const jobApplicationStatusHistory = pgTable('job_application_status_history', { id: id(), applicationId: uuid('application_id').notNull().references(() => jobApplications.id), fromStatus: text('from_status'), toStatus: text('to_status').notNull(), ...actor }, (t) => [index('job_application_history_idx').on(t.applicationId, t.occurredAt)]);

export const workSubmissions = pgTable('work_submissions', { id: id(), jobId: uuid('job_id').notNull().unique().references(() => jobs.id), workerUserId: text('worker_user_id').notNull().references(() => user.id), summary: text('summary').notNull(), status: text('status').notNull(), submittedAt: time('submitted_at').defaultNow().notNull(), reviewDeadlineAt: time('review_deadline_at').notNull() }, (t) => [index('work_submissions_review_scheduler_idx').on(t.status, t.reviewDeadlineAt)]);
export const workSubmissionStatusHistory = pgTable('work_submission_status_history', { id: id(), submissionId: uuid('submission_id').notNull().references(() => workSubmissions.id), fromStatus: text('from_status'), toStatus: text('to_status').notNull(), ...actor }, (t) => [index('work_submission_history_idx').on(t.submissionId, t.occurredAt)]);

export const disputes = pgTable('disputes', { id: id(), jobId: uuid('job_id').notNull().unique().references(() => jobs.id), openedByUserId: text('opened_by_user_id').notNull().references(() => user.id), reasonCode: text('reason_code').notNull(), description: text('description').notNull(), amountBaht: bigint('amount_baht', { mode: 'bigint' }).notNull(), status: text('status').notNull(), resolutionTargetAt: time('resolution_target_at').notNull(), resolvedAt: time('resolved_at'), createdAt: time('created_at').defaultNow().notNull(), updatedAt: time('updated_at').defaultNow().notNull() }, (t) => [check('disputes_amount_chk', sql`${t.amountBaht} > 0`)]);
export const disputeStatusHistory = pgTable('dispute_status_history', { id: id(), disputeId: uuid('dispute_id').notNull().references(() => disputes.id), fromStatus: text('from_status'), toStatus: text('to_status').notNull(), ...actor }, (t) => [index('dispute_status_history_idx').on(t.disputeId, t.occurredAt)]);
export const disputeResolutions = pgTable('dispute_resolutions', { id: id(), disputeId: uuid('dispute_id').notNull().unique().references(() => disputes.id), proposedByUserId: text('proposed_by_user_id').notNull().references(() => user.id), outcome: text('outcome').notNull(), reason: text('reason').notNull(), amountBaht: bigint('amount_baht', { mode: 'bigint' }).notNull(), policyRevisionId: uuid('policy_revision_id').notNull().references(() => moneyPolicyRevisions.id), status: text('status').notNull(), ledgerTransactionId: uuid('ledger_transaction_id').unique().references(() => ledgerTransactions.id), createdAt: time('created_at').defaultNow().notNull(), executedAt: time('executed_at') }, (t) => [check('dispute_resolutions_amount_chk', sql`${t.amountBaht} > 0`)]);
export const disputeResolutionApprovals = pgTable('dispute_resolution_approvals', { id: id(), resolutionId: uuid('resolution_id').notNull().unique().references(() => disputeResolutions.id), approverUserId: text('approver_user_id').notNull().references(() => user.id), decision: text('decision').notNull(), reason: text('reason'), decidedAt: time('decided_at').defaultNow().notNull() });
