import { sql } from 'drizzle-orm';
import { bigint, check, index, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { user } from './auth.schema';
import { ledgerTransactions } from './ledger.schema';

const time = (name: string) => timestamp(name, { withTimezone: true });
const id = () => uuid('id').defaultRandom().primaryKey();
const money = (name: string) => bigint(name, { mode: 'bigint' });

export const moneyPolicyRevisions = pgTable('money_policy_revisions', {
  id: id(), revision: bigint('revision', { mode: 'number' }).notNull().unique(), minimumTopUpBaht: money('minimum_top_up_baht').notNull(), maximumTopUpBaht: money('maximum_top_up_baht').notNull(), minimumFundedJobBaht: money('minimum_funded_job_baht').notNull(), maximumFundedJobBaht: money('maximum_funded_job_baht').notNull(), minimumEarningsConversionBaht: money('minimum_earnings_conversion_baht').notNull(), maximumEarningsConversionBaht: money('maximum_earnings_conversion_baht').notNull(), minimumPayoutBaht: money('minimum_payout_baht').notNull(), maximumPayoutBaht: money('maximum_payout_baht').notNull(),
  platformFeeBps: bigint('platform_fee_bps', { mode: 'number' }).notNull(),
  topUpProviderFeeSatang: money('top_up_provider_fee_satang').default(sql`0`).notNull(),
  topUpProviderTaxBps: bigint('top_up_provider_tax_bps', { mode: 'number' }).default(0).notNull(),
  payoutProviderFeeSatang: money('payout_provider_fee_satang').default(sql`0`).notNull(),
  payoutProviderTaxBps: bigint('payout_provider_tax_bps', { mode: 'number' }).default(0).notNull(),
  disputeTwoPersonThresholdBaht: money('dispute_two_person_threshold_baht').notNull(), quoteLifetimeSeconds: bigint('quote_lifetime_seconds', { mode: 'number' }).notNull(), reviewWindowSeconds: bigint('review_window_seconds', { mode: 'number' }).notNull(), defaultApplicationWindowSeconds: bigint('default_application_window_seconds', { mode: 'number' }).notNull(),
  authoredByUserId: text('authored_by_user_id').references(() => user.id), reason: text('reason').notNull(), effectiveFrom: time('effective_from').notNull(), effectiveUntil: time('effective_until'), createdAt: time('created_at').defaultNow().notNull(),
}, (t) => [check('money_policy_limits_chk', sql`${t.minimumTopUpBaht} > 0 and ${t.maximumTopUpBaht} >= ${t.minimumTopUpBaht} and ${t.minimumFundedJobBaht} > 0 and ${t.maximumFundedJobBaht} >= ${t.minimumFundedJobBaht} and ${t.minimumEarningsConversionBaht} > 0 and ${t.maximumEarningsConversionBaht} >= ${t.minimumEarningsConversionBaht} and ${t.minimumPayoutBaht} > 0 and ${t.maximumPayoutBaht} >= ${t.minimumPayoutBaht}`), check('money_policy_fee_chk', sql`${t.platformFeeBps} between 0 and 10000 and ${t.topUpProviderFeeSatang} >= 0 and ${t.topUpProviderTaxBps} between 0 and 10000 and ${t.payoutProviderFeeSatang} >= 0 and ${t.payoutProviderTaxBps} between 0 and 10000`), check('money_policy_durations_chk', sql`${t.quoteLifetimeSeconds} > 0 and ${t.reviewWindowSeconds} > 0 and ${t.defaultApplicationWindowSeconds} > 0`), check('money_policy_range_chk', sql`${t.effectiveUntil} is null or ${t.effectiveUntil} > ${t.effectiveFrom}`)]);

export const topUpQuotes = pgTable('top_up_quotes', { id: id(), userId: text('user_id').notNull().references(() => user.id), policyRevisionId: uuid('policy_revision_id').notNull().references(() => moneyPolicyRevisions.id), creditBaht: money('credit_baht').notNull(), chargedFeeBaht: money('charged_fee_baht').notNull(), chargedTaxBaht: money('charged_tax_baht').notNull(), paymentTotalBaht: money('payment_total_baht').notNull(), providerFeeSatang: money('provider_fee_satang').notNull(), providerTaxSatang: money('provider_tax_satang').notNull(), providerTotalSatang: money('provider_total_satang').notNull(), currency: text('currency').default('THB').notNull(), expiresAt: time('expires_at').notNull(), consumedAt: time('consumed_at'), createdAt: time('created_at').defaultNow().notNull() }, (t) => [check('top_up_quotes_amounts_chk', sql`${t.creditBaht} > 0 and ${t.chargedFeeBaht} >= 0 and ${t.chargedTaxBaht} >= 0 and ${t.paymentTotalBaht} = ${t.creditBaht} + ${t.chargedFeeBaht} + ${t.chargedTaxBaht} and ${t.providerFeeSatang} >= 0 and ${t.providerTaxSatang} >= 0 and ${t.providerTotalSatang} > 0`), check('top_up_quotes_currency_chk', sql`${t.currency} = 'THB'`), index('top_up_quotes_expiry_idx').on(t.expiresAt)]);

export const topUps = pgTable('top_ups', { id: id(), internalReference: text('internal_reference').notNull().unique(), userId: text('user_id').notNull().references(() => user.id), quoteId: uuid('quote_id').notNull().unique().references(() => topUpQuotes.id), provider: text('provider').notNull(), providerReference: text('provider_reference').unique(), creditBaht: money('credit_baht').notNull(), chargedFeeBaht: money('charged_fee_baht').notNull(), chargedTaxBaht: money('charged_tax_baht').notNull(), paymentTotalBaht: money('payment_total_baht').notNull(), providerFeeSatang: money('provider_fee_satang').notNull(), providerTaxSatang: money('provider_tax_satang').notNull(), providerTotalSatang: money('provider_total_satang').notNull(), currency: text('currency').default('THB').notNull(), qrPayload: text('qr_payload'), qrExpiresAt: time('qr_expires_at'), status: text('status').notNull(), creditedLedgerTransactionId: uuid('credited_ledger_transaction_id').unique().references(() => ledgerTransactions.id), createdAt: time('created_at').defaultNow().notNull(), updatedAt: time('updated_at').defaultNow().notNull() }, (t) => [check('top_ups_amount_chk', sql`${t.creditBaht} > 0 and ${t.chargedFeeBaht} >= 0 and ${t.chargedTaxBaht} >= 0 and ${t.paymentTotalBaht} = ${t.creditBaht} + ${t.chargedFeeBaht} + ${t.chargedTaxBaht} and ${t.providerFeeSatang} >= 0 and ${t.providerTaxSatang} >= 0 and ${t.providerTotalSatang} > 0`), check('top_ups_currency_chk', sql`${t.currency} = 'THB'`), index('top_ups_user_status_idx').on(t.userId, t.status)]);
export const topUpStatusHistory = pgTable('top_up_status_history', { id: id(), topUpId: uuid('top_up_id').notNull().references(() => topUps.id), fromStatus: text('from_status'), toStatus: text('to_status').notNull(), providerStatus: text('provider_status'), actorUserId: text('actor_user_id').references(() => user.id), source: text('source').notNull(), reason: text('reason'), occurredAt: time('occurred_at').defaultNow().notNull() }, (t) => [index('top_up_status_history_idx').on(t.topUpId, t.occurredAt)]);

export const payoutAccounts = pgTable('payout_accounts', { id: id(), userId: text('user_id').notNull().references(() => user.id), recipientType: text('recipient_type').notNull(), givenName: text('given_name').notNull(), surname: text('surname').notNull(), relationship: text('relationship').notNull(), accountCountry: text('account_country').default('TH').notNull(), accountCurrency: text('account_currency').default('THB').notNull(), bankCode: text('bank_code').notNull(), accountNumber: text('account_number').notNull(), accountHolderName: text('account_holder_name').notNull(), routingType: text('routing_type').notNull(), routingValue: text('routing_value').notNull(), maskedLastFour: text('masked_last_four').notNull(), createdAt: time('created_at').defaultNow().notNull(), retiredAt: time('retired_at') }, (t) => [check('payout_accounts_country_currency_chk', sql`${t.accountCountry} = 'TH' and ${t.accountCurrency} = 'THB'`), uniqueIndex('payout_accounts_active_user_uidx').on(t.userId).where(sql`${t.retiredAt} is null`)]);

export const payoutQuotes = pgTable('payout_quotes', { id: id(), userId: text('user_id').notNull().references(() => user.id), payoutAccountId: uuid('payout_account_id').notNull().references(() => payoutAccounts.id), policyRevisionId: uuid('policy_revision_id').notNull().references(() => moneyPolicyRevisions.id), receiptBaht: money('receipt_baht').notNull(), maximumFeeBaht: money('maximum_fee_baht').notNull(), maximumTaxBaht: money('maximum_tax_baht').notNull(), maximumDebitBaht: money('maximum_debit_baht').notNull(), quotedFeeSatang: money('quoted_fee_satang').notNull(), quotedTaxSatang: money('quoted_tax_satang').notNull(), quotedDebitSatang: money('quoted_debit_satang').notNull(), currency: text('currency').default('THB').notNull(), expiresAt: time('expires_at').notNull(), consumedAt: time('consumed_at'), createdAt: time('created_at').defaultNow().notNull() }, (t) => [check('payout_quotes_amount_chk', sql`${t.receiptBaht} > 0 and ${t.maximumFeeBaht} >= 0 and ${t.maximumTaxBaht} >= 0 and ${t.maximumDebitBaht} = ${t.receiptBaht} + ${t.maximumFeeBaht} + ${t.maximumTaxBaht} and ${t.quotedFeeSatang} >= 0 and ${t.quotedTaxSatang} >= 0 and ${t.quotedDebitSatang} > 0`), check('payout_quotes_currency_chk', sql`${t.currency} = 'THB'`), index('payout_quotes_expiry_idx').on(t.expiresAt)]);

export const payouts = pgTable('payouts', { id: id(), userId: text('user_id').notNull().references(() => user.id), quoteId: uuid('quote_id').notNull().unique().references(() => payoutQuotes.id), payoutAccountId: uuid('payout_account_id').notNull().references(() => payoutAccounts.id), destinationRecipientType: text('destination_recipient_type').notNull(), destinationGivenName: text('destination_given_name').notNull(), destinationSurname: text('destination_surname').notNull(), destinationRelationship: text('destination_relationship').notNull(), destinationAccountCountry: text('destination_account_country').notNull(), destinationAccountCurrency: text('destination_account_currency').notNull(), destinationBankCode: text('destination_bank_code').notNull(), destinationAccountNumber: text('destination_account_number').notNull(), destinationAccountHolderName: text('destination_account_holder_name').notNull(), destinationRoutingType: text('destination_routing_type').notNull(), destinationRoutingValue: text('destination_routing_value').notNull(), provider: text('provider').notNull(), providerReference: text('provider_reference').unique(), principalBaht: money('principal_baht').notNull(), maximumFeeBaht: money('maximum_fee_baht').notNull(), maximumTaxBaht: money('maximum_tax_baht').notNull(), maximumDebitBaht: money('maximum_debit_baht').notNull(), actualFeeSatang: money('actual_fee_satang'), actualTaxSatang: money('actual_tax_satang'), actualDebitSatang: money('actual_debit_satang'), currency: text('currency').default('THB').notNull(), status: text('status').notNull(), reserveLedgerTransactionId: uuid('reserve_ledger_transaction_id').notNull().unique().references(() => ledgerTransactions.id), finalLedgerTransactionId: uuid('final_ledger_transaction_id').unique().references(() => ledgerTransactions.id), createdAt: time('created_at').defaultNow().notNull(), updatedAt: time('updated_at').defaultNow().notNull() }, (t) => [check('payouts_amount_chk', sql`${t.principalBaht} > 0 and ${t.maximumFeeBaht} >= 0 and ${t.maximumTaxBaht} >= 0 and ${t.maximumDebitBaht} = ${t.principalBaht} + ${t.maximumFeeBaht} + ${t.maximumTaxBaht}`), check('payouts_currency_chk', sql`${t.currency} = 'THB' and ${t.destinationAccountCountry} = 'TH' and ${t.destinationAccountCurrency} = 'THB'`), uniqueIndex('payouts_active_user_uidx').on(t.userId).where(sql`${t.status} in ('CREATING','PENDING','AWAITING_RECONCILIATION')`)]);
export const payoutStatusHistory = pgTable('payout_status_history', { id: id(), payoutId: uuid('payout_id').notNull().references(() => payouts.id), fromStatus: text('from_status'), toStatus: text('to_status').notNull(), providerStatus: text('provider_status'), actorUserId: text('actor_user_id').references(() => user.id), source: text('source').notNull(), reason: text('reason'), occurredAt: time('occurred_at').defaultNow().notNull() }, (t) => [index('payout_status_history_idx').on(t.payoutId, t.occurredAt)]);

export const payoutCancellationAttempts = pgTable('payout_cancellation_attempts', { id: id(), payoutId: uuid('payout_id').notNull().references(() => payouts.id), adminUserId: text('admin_user_id').notNull().references(() => user.id), reason: text('reason').notNull(), status: text('status').notNull(), providerResponse: jsonb('provider_response'), attemptedAt: time('attempted_at').defaultNow().notNull() }, (t) => [index('payout_cancellation_attempts_payout_idx').on(t.payoutId, t.attemptedAt)]);
