// One identity list for the dedicated Member seed and debug login. No special Member role.
export const demoMembers = [
  {
    key: 'account-1',
    email: 'nattapong.srisawat@ku.th',
    firstName: 'Nattapong',
    lastName: 'Srisawat',
    department: 'Software and Knowledge Engineering',
    bio: 'I build useful mobile apps and small tools for campus clubs.',
    studentId: '6501000000',
    telephone: '0810000000',
    academicYear: 2565,
  },
  {
    key: 'account-2',
    email: 'warisara.boonmee@ku.th',
    firstName: 'Warisara',
    lastName: 'Boonmee',
    department: 'Marketing',
    bio: 'I enjoy event photography and helping campus clubs reach new members.',
    studentId: '6501000001',
    telephone: '0810000001',
    academicYear: 2566,
  },
  {
    key: 'account-3',
    email: 'thanakrit.chaiyasit@ku.th',
    firstName: 'Thanakrit',
    lastName: 'Chaiyasit',
    department: 'Economics',
    bio: 'I turn survey responses into clear charts and practical recommendations.',
    studentId: '6501000002',
    telephone: '0810000002',
    academicYear: 2567,
  },
  {
    key: 'account-4',
    email: 'supitcha.wongsakul@ku.th',
    firstName: 'Supitcha',
    lastName: 'Wongsakul',
    department: 'Bachelor of Accountancy',
    bio: 'I organise project budgets and make spreadsheets easy to understand.',
    studentId: '6501000003',
    telephone: '0810000003',
    academicYear: 2568,
  },
  {
    key: 'account-5',
    email: 'kritchapon.phromma@ku.th',
    firstName: 'Kritchapon',
    lastName: 'Phromma',
    department: 'Tropical Agriculture',
    bio: 'I grow herbs and volunteer in the university community garden.',
    studentId: '6501000004',
    telephone: '0810000004',
    academicYear: 2565,
  },
  {
    key: 'account-6',
    email: 'aphinya.sukjai@ku.th',
    firstName: 'Aphinya',
    lastName: 'Sukjai',
    department: 'Integrated Tourism Management',
    bio: 'I plan walking tours and welcoming activities for visiting students.',
    studentId: '6501000005',
    telephone: '0810000005',
    academicYear: 2566,
  },
  {
    key: 'account-7',
    email: 'pattarapon.ruangrit@ku.th',
    firstName: 'Pattarapon',
    lastName: 'Ruangrit',
    department: 'Business Administration',
    bio: 'I coordinate club activities and help teams keep their projects on track.',
    studentId: '6501000006',
    telephone: '0810000006',
    academicYear: 2567,
  },
  {
    key: 'account-8',
    email: 'chutimon.thepsuriya@ku.th',
    firstName: 'Chutimon',
    lastName: 'Thepsuriya',
    department: 'Communicative Thai Language for Foreigners',
    bio: 'I write bilingual campus guides and help international students practise Thai.',
    studentId: '6501000007',
    telephone: '0810000007',
    academicYear: 2568,
  },
  {
    key: 'account-9',
    email: 'ekkapop.wattana@ku.th',
    firstName: 'Ekkapop',
    lastName: 'Wattana',
    department: 'Entrepreneurial Economics',
    bio: 'I research student business ideas and build clear presentation decks.',
    studentId: '6501000008',
    telephone: '0810000008',
    academicYear: 2565,
  },
  {
    key: 'account-10',
    email: 'nichakan.kaewmanee@ku.th',
    firstName: 'Nichakan',
    lastName: 'Kaewmanee',
    department: 'Marketing',
    bio: 'I design posters and social media content for student events.',
    studentId: '6501000009',
    telephone: '0810000009',
    academicYear: 2566,
  },
] as const;
