export const fixedTagNames = [
  '3D Modeling & Animation',
  'Academic Writing',
  'Accounting & Bookkeeping',
  'Agricultural Field Work',
  'Animal Care & Pet Sitting',
  'Audio Production & Music',
  'Backend Development',
  'Biology Tutoring',
  'Business Planning',
  'Campus Errand & Delivery',
  'Campus Tour & Guiding',
  'Chemistry Tutoring',
  'Chinese Translation',
  'Computer Science Tutoring',
  'Content Writing & Copywriting',
  'Cybersecurity',
  'Data Analysis',
  'Data Entry & Transcription',
  'Data Visualization',
  'Database Management',
  'DevOps & Cloud Infrastructure',
  'Document Printing & Pickup',
  'English Tutoring',
  'English-Thai Translation',
  'Event Photography & Videography',
  'Event Staff & Ushering',
  'Exam Preparation',
  'Food Science & Quality Testing',
  'Frontend Development',
  'Fullstack Development',
  'Game Development',
  'General Assistance',
  'Graphic Design',
  'Illustration & Digital Art',
  'Japanese Translation',
  'Logo & Branding Design',
  'MC & Public Speaking',
  'Machine Learning & AI',
  'Market Research',
  'Marketing Campaign',
  'Mathematics Tutoring',
  'Mobile App Development',
  'Motion Graphics',
  'Moving & Heavy Lifting',
  'Physics Tutoring',
  'Plant Care & Gardening',
  'Presentation & Slide Design',
  'Proofreading & Editing',
  'Queue Standing & Spot Holding',
  'Social Media Management',
  'Software Testing & QA',
  'Stage & Equipment Setup',
  'Statistical Analysis',
  'Survey & Field Data Collection',
  'Thai-English Translation',
  'UI/UX Design',
  'Video Editing & Post-Production',
] as const;

export type FixedTagName = (typeof fixedTagNames)[number];
