-- Work Chat schema design draft
--
-- LEGACY REFERENCE: use docs/quest/work-chat-system-target.md for the accepted
-- Work Chat workflow and constraints. This draft contains older attachment,
-- message, and status assumptions. Reconcile it before using it for implementation.
--
-- Design-only SQL for BE-174.
-- This file is not a Drizzle migration. Do not run it against a shared or
-- production database. It intentionally contains no runtime functions,
-- triggers, seed data, or migration journal entry.
--
-- Target schema dependencies:
--   public.quest(id uuid)
--   public.file(id uuid)
--   public.auth_user(id uuid)
--
-- UUIDs are database-generated by default. External identifiers such as
-- client_message_id and event_id remain opaque strings.

-- Required by the temporal Membership exclusion constraint below.
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TYPE public.chat_membership_role AS ENUM (
  'HIRER',
  'WORKER'
);

CREATE TYPE public.chat_message_kind AS ENUM (
  'USER',
  'SYSTEM'
);

CREATE TYPE public.chat_attachment_status AS ENUM (
  'QUARANTINED',
  'VALIDATED',
  'REJECTED',
  'CONSUMED',
  'HIDDEN',
  'EXPIRED'
);

CREATE TABLE public.chat_conversation (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  quest_id uuid NOT NULL,
  quest_title varchar(200) NOT NULL,
  quest_status varchar(50) NOT NULL,
  next_sequence bigint NOT NULL DEFAULT 1,
  read_only_at timestamptz,
  archived_at timestamptz,
  latest_terminal_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT chat_conversation_quest_id_key UNIQUE (quest_id),
  CONSTRAINT chat_conversation_quest_fk
    FOREIGN KEY (quest_id)
    REFERENCES public.quest (id)
    ON DELETE RESTRICT,
  CONSTRAINT chat_conversation_title_check
    CHECK (btrim(quest_title) <> ''),
  CONSTRAINT chat_conversation_status_snapshot_check
    CHECK (btrim(quest_status) <> ''),
  CONSTRAINT chat_conversation_next_sequence_check
    CHECK (next_sequence > 0),
  CONSTRAINT chat_conversation_terminal_time_check
    CHECK (
      latest_terminal_at IS NULL
      OR read_only_at IS NOT NULL
    ),
  CONSTRAINT chat_conversation_lifecycle_time_order_check
    CHECK (
      (latest_terminal_at IS NULL OR read_only_at IS NULL OR latest_terminal_at <= read_only_at)
      AND (archived_at IS NULL OR read_only_at IS NULL OR archived_at >= read_only_at)
    )
);

COMMENT ON TABLE public.chat_conversation IS
  'One Work Conversation for one Quest. Soft deletion keeps the Quest association and retained history.';
COMMENT ON COLUMN public.chat_conversation.quest_title IS
  'Quest title snapshot. It is not a live replacement for quest.title.';
COMMENT ON COLUMN public.chat_conversation.quest_status IS
  'Quest status snapshot stored as a bounded varchar so historical values do not depend on the Quest enum.';
COMMENT ON COLUMN public.chat_conversation.next_sequence IS
  'Next Conversation sequence to reserve. The Service increments it in the Message transaction.';
COMMENT ON COLUMN public.chat_conversation.latest_terminal_at IS
  'Time of the latest terminal Quest transition used by retention policy.';

CREATE TABLE public.chat_membership (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  member_id uuid,
  role public.chat_membership_role NOT NULL,
  joined_at timestamptz NOT NULL,
  left_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT chat_membership_conversation_id_id_key
    UNIQUE (conversation_id, id),
  CONSTRAINT chat_membership_conversation_fk
    FOREIGN KEY (conversation_id)
    REFERENCES public.chat_conversation (id)
    ON DELETE RESTRICT,
  CONSTRAINT chat_membership_member_fk
    FOREIGN KEY (member_id)
    REFERENCES public.auth_user (id)
    ON DELETE SET NULL,
  CONSTRAINT chat_membership_window_order_check
    CHECK (left_at IS NULL OR left_at >= joined_at),
  CONSTRAINT chat_membership_created_time_check
    CHECK (created_at >= joined_at)
);

COMMENT ON TABLE public.chat_membership IS
  'One inclusive Work Membership Window for a Member in a Work Conversation.';
COMMENT ON COLUMN public.chat_membership.member_id IS
  'Nullable after Member deletion. The Membership row remains for retained history and displays Former member.';
COMMENT ON COLUMN public.chat_membership.left_at IS
  'Inclusive window end. A Message created at left_at remains visible to this Membership.';

-- A Member cannot have overlapping windows in the same Conversation. Inclusive
-- bounds also require a later rejoin to start after the previous left_at.
ALTER TABLE public.chat_membership
  ADD CONSTRAINT chat_membership_non_overlapping_window_excl
  EXCLUDE USING gist (
    conversation_id WITH =,
    member_id WITH =,
    tstzrange(
      joined_at,
      COALESCE(left_at, 'infinity'::timestamptz),
      '[]'
    ) WITH &&
  )
  WHERE (member_id IS NOT NULL);

CREATE UNIQUE INDEX chat_membership_one_active_hirer_uidx
  ON public.chat_membership (conversation_id)
  WHERE role = 'HIRER'::public.chat_membership_role
    AND left_at IS NULL;

CREATE INDEX chat_membership_member_conversation_idx
  ON public.chat_membership (member_id, conversation_id, joined_at DESC)
  WHERE member_id IS NOT NULL;

CREATE INDEX chat_membership_conversation_window_idx
  ON public.chat_membership (conversation_id, joined_at, left_at);

CREATE TABLE public.chat_message (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  sequence bigint NOT NULL,
  kind public.chat_message_kind NOT NULL,
  sender_membership_id uuid,
  client_message_id varchar(128),
  content_text varchar(4000),
  system_type varchar(100),
  system_payload jsonb,
  event_id varchar(255),
  deleted_at timestamptz,
  retention_eligible_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT chat_message_conversation_sequence_key
    UNIQUE (conversation_id, sequence),
  CONSTRAINT chat_message_conversation_fk
    FOREIGN KEY (conversation_id)
    REFERENCES public.chat_conversation (id)
    ON DELETE RESTRICT,
  CONSTRAINT chat_message_sender_membership_fk
    FOREIGN KEY (conversation_id, sender_membership_id)
    REFERENCES public.chat_membership (conversation_id, id)
    ON DELETE SET NULL (sender_membership_id),
  CONSTRAINT chat_message_sequence_check
    CHECK (sequence > 0),
  CONSTRAINT chat_message_content_text_check
    CHECK (content_text IS NULL OR btrim(content_text) <> ''),
  CONSTRAINT chat_message_kind_fields_check
    CHECK (
      (
        kind = 'USER'::public.chat_message_kind
        AND sender_membership_id IS NOT NULL
        AND client_message_id IS NOT NULL
        AND btrim(client_message_id) <> ''
        AND event_id IS NULL
        AND system_type IS NULL
        AND system_payload IS NULL
      )
      OR (
        kind = 'SYSTEM'::public.chat_message_kind
        AND client_message_id IS NULL
        AND event_id IS NOT NULL
        AND btrim(event_id) <> ''
        AND system_type IS NOT NULL
        AND btrim(system_type) <> ''
        AND system_payload IS NOT NULL
        AND jsonb_typeof(system_payload) = 'object'
      )
    ),
  CONSTRAINT chat_message_deleted_time_check
    CHECK (deleted_at IS NULL OR deleted_at >= created_at),
  CONSTRAINT chat_message_retention_time_check
    CHECK (
      retention_eligible_at IS NULL
      OR retention_eligible_at >= created_at
    )
);

COMMENT ON TABLE public.chat_message IS
  'Immutable ordered Message record, except for retention and soft-delete updates.';
COMMENT ON COLUMN public.chat_message.sequence IS
  'Strictly increasing server-assigned position inside one Conversation. Gaps after rollback are allowed.';
COMMENT ON COLUMN public.chat_message.system_payload IS
  'Structured event data for a System Message. The Service owns the event protocol.';
COMMENT ON COLUMN public.chat_message.sender_membership_id IS
  'Nullable for anonymized former Members. New User Messages require a current sender Membership in the Service.';

-- A retry with the same Chat Membership and clientMessageId finds the original
-- Message. Soft-deleted rows remain in this key space. Payload comparison, if
-- required, is a Service rule.
CREATE UNIQUE INDEX chat_message_client_message_id_uidx
  ON public.chat_message (sender_membership_id, client_message_id)
  WHERE kind = 'USER'::public.chat_message_kind;

-- event_id is a global System Message identity. A repeated lifecycle event
-- must not create another System Message in another Conversation.
CREATE UNIQUE INDEX chat_message_event_id_uidx
  ON public.chat_message (event_id)
  WHERE kind = 'SYSTEM'::public.chat_message_kind;

CREATE INDEX chat_message_conversation_created_idx
  ON public.chat_message (conversation_id, created_at DESC, sequence DESC);

CREATE INDEX chat_message_retention_eligible_idx
  ON public.chat_message (retention_eligible_at)
  WHERE retention_eligible_at IS NOT NULL;

CREATE TABLE public.chat_attachment (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  uploaded_by_member_id uuid,
  file_id uuid,
  status public.chat_attachment_status NOT NULL DEFAULT 'QUARANTINED',
  original_filename varchar(255) NOT NULL,
  mime_type varchar(255) NOT NULL,
  size_bytes bigint NOT NULL,
  expires_at timestamptz,
  validated_at timestamptz,
  rejected_at timestamptz,
  rejection_reason text,
  consumed_at timestamptz,
  hidden_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT chat_attachment_conversation_fk
    FOREIGN KEY (conversation_id)
    REFERENCES public.chat_conversation (id)
    ON DELETE RESTRICT,
  CONSTRAINT chat_attachment_uploaded_by_membership_fk
    FOREIGN KEY (conversation_id, uploaded_by_member_id)
    REFERENCES public.chat_membership (conversation_id, id)
    ON DELETE SET NULL (uploaded_by_member_id),
  CONSTRAINT chat_attachment_file_fk
    FOREIGN KEY (file_id)
    REFERENCES public.file (id)
    ON DELETE RESTRICT,
  CONSTRAINT chat_attachment_filename_check
    CHECK (btrim(original_filename) <> ''),
  CONSTRAINT chat_attachment_mime_type_check
    CHECK (btrim(mime_type) <> ''),
  CONSTRAINT chat_attachment_size_check
    CHECK (size_bytes > 0),
  CONSTRAINT chat_attachment_initial_file_check
    CHECK (
      status NOT IN (
        'QUARANTINED'::public.chat_attachment_status,
        'REJECTED'::public.chat_attachment_status
      )
      OR file_id IS NULL
    ),
  CONSTRAINT chat_attachment_ready_file_check
    CHECK (
      status NOT IN (
        'VALIDATED'::public.chat_attachment_status,
        'CONSUMED'::public.chat_attachment_status,
        'HIDDEN'::public.chat_attachment_status
      )
      OR file_id IS NOT NULL
    ),
  CONSTRAINT chat_attachment_rejected_fields_check
    CHECK (
      (
        status = 'REJECTED'::public.chat_attachment_status
        AND rejected_at IS NOT NULL
        AND rejection_reason IS NOT NULL
        AND btrim(rejection_reason) <> ''
      )
      OR (
        status <> 'REJECTED'::public.chat_attachment_status
        AND rejected_at IS NULL
        AND rejection_reason IS NULL
      )
    ),
  CONSTRAINT chat_attachment_consumed_time_check
    CHECK (
      status <> 'CONSUMED'::public.chat_attachment_status
      OR consumed_at IS NOT NULL
    ),
  CONSTRAINT chat_attachment_hidden_time_check
    CHECK (
      status <> 'HIDDEN'::public.chat_attachment_status
      OR hidden_at IS NOT NULL
    ),
  CONSTRAINT chat_attachment_deleted_time_check
    CHECK (deleted_at IS NULL OR deleted_at >= created_at)
);

COMMENT ON TABLE public.chat_attachment IS
  'Private Attachment intended for one Work Conversation. Basic file validation is represented by VALIDATED.';
COMMENT ON COLUMN public.chat_attachment.uploaded_by_member_id IS
  'Chat Membership that created the Attachment. The composite foreign key keeps the uploader in this Work Conversation.';
COMMENT ON COLUMN public.chat_attachment.file_id IS
  'NULL until validation. A File may be reused by creating a new Attachment, while each Attachment is linked to one Message at most.';
COMMENT ON COLUMN public.chat_attachment.expires_at IS
  'Expiry deadline for an unconsumed upload. The retention worker owns later cleanup.';
COMMENT ON COLUMN public.chat_attachment.rejection_reason IS
  'Non-content reason for a failed basic validation.';

CREATE INDEX chat_attachment_conversation_created_idx
  ON public.chat_attachment (conversation_id, created_at DESC);

CREATE INDEX chat_attachment_file_idx
  ON public.chat_attachment (file_id)
  WHERE file_id IS NOT NULL;

CREATE INDEX chat_attachment_status_expiry_idx
  ON public.chat_attachment (status, expires_at)
  WHERE expires_at IS NOT NULL;

CREATE INDEX chat_attachment_uploader_idx
  ON public.chat_attachment (uploaded_by_member_id, conversation_id, created_at DESC)
  WHERE uploaded_by_member_id IS NOT NULL;

CREATE TABLE public.chat_message_attachment (
  message_id uuid NOT NULL,
  attachment_id uuid NOT NULL,
  position smallint NOT NULL,
  attached_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT chat_message_attachment_pk
    PRIMARY KEY (message_id, attachment_id),
  CONSTRAINT chat_message_attachment_message_fk
    FOREIGN KEY (message_id)
    REFERENCES public.chat_message (id)
    ON DELETE RESTRICT,
  CONSTRAINT chat_message_attachment_attachment_fk
    FOREIGN KEY (attachment_id)
    REFERENCES public.chat_attachment (id)
    ON DELETE RESTRICT,
  CONSTRAINT chat_message_attachment_attachment_once_key
    UNIQUE (attachment_id),
  CONSTRAINT chat_message_attachment_message_position_key
    UNIQUE (message_id, position),
  CONSTRAINT chat_message_attachment_position_check
    CHECK (position BETWEEN 1 AND 5)
);

COMMENT ON TABLE public.chat_message_attachment IS
  'One-time Message-to-Attachment link. The Service changes the Attachment to CONSUMED in the same transaction.';

CREATE TABLE public.chat_read_cursor (
  conversation_id uuid NOT NULL,
  membership_id uuid NOT NULL,
  last_read_sequence bigint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT chat_read_cursor_pk
    PRIMARY KEY (conversation_id, membership_id),
  CONSTRAINT chat_read_cursor_membership_fk
    FOREIGN KEY (conversation_id, membership_id)
    REFERENCES public.chat_membership (conversation_id, id)
    ON DELETE RESTRICT,
  CONSTRAINT chat_read_cursor_sequence_check
    CHECK (last_read_sequence >= 0)
);

COMMENT ON TABLE public.chat_read_cursor IS
  'Private acknowledgement position for one Member Membership in one Conversation.';
COMMENT ON COLUMN public.chat_read_cursor.last_read_sequence IS
  'Furthest acknowledged Conversation sequence. The Service only moves it forward.';

-- Service invariants intentionally left outside CHECK constraints:
--   * A new USER Message must have text or at least one Message Attachment. A
--     maximum of five Attachments is represented by the position check above.
--   * Message and Attachment conversation_id values must match.
--   * A Message Attachment must be created only for a VALIDATED, unused
--     Attachment uploaded by the same Chat Membership as the User Message.
--   * Sharing a File creates a new Chat Attachment. A Chat Attachment is linked
--     to one Message at most.
--   * A Read Cursor update must not lower last_read_sequence and must target a
--     Message visible in the caller's Work Membership Window.
--   * Access queries must apply the inclusive joined_at/left_at visibility
--     window and exclude soft-deleted content from normal Member views.
